# Generated by Django 3.2.11 on 2022-03-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_song_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='song_id',
            new_name='current_song',
        ),
    ]
